destinasi/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DestinasiController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\LupaPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('home', function () {
    return view('tamplate');
});

Route::get('dashboard', function () {
    return view('template_admin');
});

Route::controller(DestinasiController::class)->name('desitnasi.')->prefix('destinasi')->group(function () {
    //nama prefix //nama function di controller // name route
    Route::get('/list', 'listDestinasi')->name('list');
    Route::get('/detail/{id}', 'detailDestinasi')->name('detail');
});

Route::controller(LoginController::class)->name('login.')->prefix('login')->group(function () {
    //nama prefix //nama function di controller // name route
    Route::get('/', 'formLogin')->name('login');
    Route::post('/proses-login', 'ProsesLogin')->name('proses-login');
}); 

Route::controller(RegisterController::class)->name('register.')->prefix('register')->group(function () {
    //nama prefix //nama function di controller // name route
    Route::get('/', 'formRegister')->name('register');
    Route::post('/simpan-register', 'simpanRegister')->name('simpan-register');
}); 

Route::controller(AdminController::class)->name('admin.')->middleware('CekLogin:admin')->prefix('admin')->group(function () {
    //nama prefix //nama function di controller // name route
    Route::get('/', 'dashboardAdmin')->name('dashboard');
    Route::get('/tambah-destinasi', 'addDestinasi')->name('add');
    Route::get('/list-destinasi', 'listDestinasi')->name('list');
    Route::post('/simpan-data', 'simpanData')->name('simpan-data');
    Route::get('/form-edit/{id}', 'formEdit')->name('form-edit');
    Route::post('/edit-data/{id}', 'editData')->name('edit-data');
    Route::get('/delete-data/{id}', 'deleteData')->name('delete-data');
}); 

Route::controller(UserController::class)->name('user.')->middleware('CekLogin:user')->prefix('user')->group(function () {
    //nama prefix //nama function di controller // name route
    Route::get('/', 'dashboardUser')->name('dashboard');
    Route::get('/tambah-destinasi', 'addDestinasi')->name('add');
    Route::get('/list-destinasi', 'listDestinasi')->name('list');
    Route::get('/list-destinasi', 'listDestinasi')->name('list');
    Route::post('/simpan-data', 'simpanData')->name('simpan-data');
    Route::get('/form-edit/{id}', 'formEdit')->name('form-edit');
    Route::post('/edit-data/{id}', 'editData')->name('edit-data');
    Route::get('/delete-data/{id}', 'deleteData')->name('delete-data');
}); 

Route::controller(LogoutController::class)->name('logout.')->prefix('logout')->group(function () {
    //nama prefix //nama function di controller // name route
    Route::get('/', 'logout')->name('proses');
});

Route::controller(LupaPasswordController::class)->name('forgot.')->prefix('forgot')->group(function () {
    //nama prefix //nama function di controller // name route
    Route::get('/', 'formLupaPassword')->name('form-forgot');
    Route::post('/proses', 'prosesLupaPassword')->name('proses');
    Route::get('/reset-password/{token}', 'resetPassword')->name('reset-password');
    Route::post('/proses-reset', 'prosesResetPassword')->name('proses-reset');
});

destinasi/app/Models/Destinasi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Destinasi extends Model
{
    protected $table = "destinasi";

    public $timestamps = true;

    protected $fillable = [
        'nama',
        'alamat',
        'deskripsi',
        'gambar',
        'id_author'
    ];
}

destinasi/app/Http/Controllers/DestinasiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Destinasi;
use App\Models\Pengguna;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class DestinasiController extends Controller
{
    public function listDestinasi()
    {
        $dataDestinasi = Destinasi::select('destinasi.id', 'destinasi.nama', 'destinasi.alamat','destinasi.deskripsi' , 'destinasi.gambar', 'destinasi.jumlah_dilihat', 'pengguna.name')
        ->join('pengguna', 'pengguna.id', '=', 'destinasi.id_author')
        ->get();
        return view('destinasi.list_destinasi', compact('dataDestinasi'));
    }

    public function detailDestinasi($id)
    {
        $getDataById = Destinasi::select('destinasi.id', 'destinasi.nama', 'destinasi.alamat','destinasi.deskripsi' , 'destinasi.gambar', 'pengguna.name')
        ->join('pengguna', 'pengguna.id', '=', 'destinasi.id_author')
        ->where('destinasi.id', $id)->first();

        // Perbarui jumlah dilihat pada database
        Destinasi::where('id', $id)->increment('jumlah_dilihat');

        return view('destinasi.deskripsi_destinasi',compact('getDataById'));
    }
}

destinasi/resources/views/destinasi/deskripsi_destinasi.blade.php
@extends('../tamplate')

@section('content_detail')

<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="row">
            <div class="col-lg-8">
                <!-- Blog Detail Start -->
                <div class="pb-3">
                    <div class="blog-item">
                        <div class="position-relative">
                            <img class="img-fluid w-100" src="{{ asset('img/'.$getDataById->gambar) }}" alt="">
                        </div>
                    </div>
                    <div class="bg-white mb-3" style="padding: 30px;">
                        <div class="d-flex mb-3">
                            <p class="text-primary text-uppercase text-decoration-none" href="">{{ $getDataById->alamat }}</p>
                        </div>
                        <h2 class="mb-3">{{ $getDataById->nama }}</h2>
                        <p>{{ $getDataById->deskripsi }}</p>
                    </div>
                </div>
                <!-- Blog Detail End -->


            </div>

            <div class="col-lg-4 mt-5 mt-lg-0">
                <!-- Author Bio -->
                <div class="d-flex flex-column text-center bg-white mb-5 py-5 px-4">
                    <img src="{{ asset('style_user/img/profile.jpeg') }}" class="img-fluid mx-auto mb-3" style="width: 100px;">
                    <h3 class="text-primary mb-3">{{ $getDataById->name }}</h3>
                    <div class="d-flex justify-content-center">
                        <a class="text-primary px-2" href="">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a class="text-primary px-2" href="">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a class="text-primary px-2" href="">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                        <a class="text-primary px-2" href="">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a class="text-primary px-2" href="">
                            <i class="fab fa-youtube"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>  
@endsection

    
    

destinasi/resources/views/destinasi/list_destinasi.blade.php
@extends('../tamplate')

@section('list_destination')

    <!-- Destination Start -->
    <div class="container py-5">    
    <div class="row pb-3">
        @foreach ($dataDestinasi as $row)
            <div class="col-md-6 mb-4 pb-2">
                <div class="blog-item">
                    <div class="position-relative">
                        <img class="img-fluid w-100" src="{{ asset('img/'.$row->gambar) }}" alt="" style="width: 200px; height: 400px;">
                    </div>
                    <div class="bg-white p-4">
                        <div class="d-flex mb-2">
                            <p class="text-primary text-uppercase text-decoration-none" >{{ $row->alamat }} | <i class="far fa-eye"></i> {{ $row->jumlah_dilihat }}</p><br>
                            <p class="text-primary text-uppercase text-decoration-none" ></p>
                        </div>
                        <a class="h5 m-0 text-decoration-none" href="{{ route('desitnasi.detail', $row->id)}}">{{ $row->nama }}</a>
                    </div>
                </div>
            </div>
        @endforeach
        

    </div>
  </div>
</div>
  <!-- Destination Start -->
  
@endsection